### ISSUE TITLE
XML to JAVA XPATH array index doesn't work under Oracle JDK 1.8

### ISSUE THREAD

**Issue by RapperChen** [smooks/smooks#141]
We are using smooks 1.7 to transform data from XML to Java Object. We found that the xpath array index 
/xxx/yyy/zzz[1] doesn't work under oracle JDK 1.8, and hit a NullPointerException. 

java.lang.NullPointerException
	at org.milyn.cdr.xpath.SelectorStep.getEvaluators(SelectorStep.java:365)
	at org.milyn.cdr.xpath.SelectorStep.getEvaluators(SelectorStep.java:361)
	at org.milyn.delivery.sax.SAXContentDeliveryConfig.addIndexCounters(SAXContentDeliveryConfig.java:233)
	at org.milyn.delivery.sax.SAXContentDeliveryConfig.addIndexCounters(SAXContentDeliveryConfig.java:215)
	at org.milyn.delivery.ContentDeliveryConfigBuilder.createConfig(ContentDeliveryConfigBuilder.java:218)
	at org.milyn.delivery.ContentDeliveryConfigBuilder.getConfig(ContentDeliveryConfigBuilder.java:148)
	at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:91)
	at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:65)
	at org.milyn.Smooks.createExecutionContext(Smooks.java:418)
	at org.milyn.Smooks.createExecutionContext(Smooks.java:376)
	at org.milyn.Smooks.filterSource(Smooks.java:456)
	at com.hsbc.cmb.osl.integration.common.etl.processor.R7EtlHandlerFormValueCompareTest.prepareR7IpObject(R7EtlHandlerFormValueCompareTest.java:164)
	at com.hsbc.cmb.osl.integration.common.etl.processor.R7EtlHandlerFormValueCompareTest.testR7FullMapping(R7EtlHandlerFormValueCompareTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)

**Comment by asgs** [comment]
can you post a sample XML and Java testcase to reproduce the issue mentioned above?

**Comment by RapperChen** [comment]
To simulate our test, I have downloaded the sample project xml-to-java, and made some changes as below.

smooks-config.xml
<?xml version="1.0"?>
<smooks-resource-list xmlns="http://www.milyn.org/xsd/smooks-1.1.xsd" xmlns:jb="http://www.milyn.org/xsd/smooks/javabean-1.2.xsd">

    
    <jb:bean beanId="order" class="org.milyn.javabean.decoders.demo.Order" createOnElement="order">
        <jb:wiring property="header" beanIdRef="header" />
        <jb:wiring property="orderItems" beanIdRef="orderItems" />
    </jb:bean>

    
    <jb:bean beanId="orderItems" class="java.util.ArrayList" createOnElement="order/order-items/order-item/order-item">
        <jb:wiring beanIdRef="orderItem" />
    </jb:bean>

    
    <jb:bean beanId="header" class="org.milyn.javabean.decoders.demo.Header" createOnElement="header">
        <jb:value property="date" decoder="Date" data="header/date">
            <jb:decodeParam name="format">EEE MMM dd HH:mm:ss z yyyy</jb:decodeParam>
            <jb:decodeParam name="locale-language">en</jb:decodeParam>
            <jb:decodeParam name="locale-country">IE</jb:decodeParam>
        </jb:value>
        <jb:value property="customerNumber" decoder="Long" data="header/customer/@number" />
        <jb:value property="customerName" data="header/customer" />
    </jb:bean>

    
    <jb:bean beanId="orderItem" class="org.milyn.javabean.decoders.demo.OrderItem" createOnElement="order/order-items/order-item/order-item[1]/product">
        <jb:value property="productId" decoder="Long" data="order/order-items/order-item/order-item/product" />
        <jb:value property="quantity" decoder="Integer" data="order/order-items/order-item/order-item/quantity" />
        <jb:value property="price" decoder="Double" data="order/order-items/order-item/order-item/price" />
    </jb:bean>


</smooks-resource-list>

input-message.xml

<order>
    <header>
        <date>Wed Nov 15 13:45:28 EST 2006</date>
        <customer number="123123">Joe</customer>
    </header>
    <order-items>
        <order-item>
            <order-item>
                <product>111</product>
                <quantity>2</quantity>
                <price>8.90</price>
            </order-item>

            <order-item>
                <product>222</product>
                <quantity>7</quantity>
                <price>5.20</price>
            </order-item>
        </order-item>
    </order-items>
</order>

**Comment by RapperChen** [comment]
input-message.xml

<order>
    <header>
        <date>Wed Nov 15 13:45:28 EST 2006</date>
        <customer number="123123">Joe</customer>
    </header>
    <order-items>
        <order-item>
            <order-item>
                <product>111</product>
                <quantity>2</quantity>
                <price>8.90</price>
            </order-item>

            <order-item>
                <product>222</product>
                <quantity>7</quantity>
                <price>5.20</price>
            </order-item>
        </order-item>
    </order-items>
</order>

**Comment by RapperChen** [comment]
<order>
    <header1>
        <date1>Wed Nov 15 13:45:28 EST 2006</date1>
        <customer number="123123">Joe</customer>
    </header1>
    <order-items>
        <order-item>
            <order-item>
                <product>111</product>
                <quantity>2</quantity>
                <price>8.90</price>
            </order-item>

            <order-item>
                <product>222</product>
                <quantity>7</quantity>
                <price>5.20</price>
            </order-item>
        </order-item>
    </order-items>
</order>

**Comment by RapperChen** [comment]
<order-items>
        <order-item>
            <order-item>
                <product>111</product>
                <quantity>2</quantity>
                <price>8.90</price>
            </order-item>

            <order-item>
                <product>222</product>
                <quantity>7</quantity>
                <price>5.20</price>
            </order-item>
        </order-item>
    </order-items>

**Comment by RapperChen** [comment]
the input-message.xml  can't be displayed correctly in the comment. 

I have added another node "order-item" as order-items' child.
