### ISSUE TITLE
Smooks failed to filter source - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by sohaib93** [smooks/smooks#149]
I am relatively new to EDIFACT/D96A. I am trying to convert from edi using the D96AInterchangeFactory.

Here is what i have:
I have the D96AInterchangeFactory instance that i use to call the fromUNEdifact method. What happens is that once the control goes into Smooks i get the following error:

```
 org.milyn.SmooksException: Failed to filter source.
    at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:97)
    at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:64)
    at org.milyn.Smooks._filter(Smooks.java:526)
    at org.milyn.Smooks.filterSource(Smooks.java:482)
    at .
    .
    .

org.milyn.smooks.edi.unedifact.UNEdifactReader.parse(UNEdifactReader.java:75)
    at org.milyn.delivery.sax.SAXParser.parse(SAXParser.java:76)
    at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:86)
    ... 22 more
    Caused by: java.lang.NoSuchMethodError: sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class;
    at
    . .
    org.milyn.javabean.BeanInstanceCreator.createAndSetBean(BeanInstanceCreator.java:296)
        at org.milyn.javabean.BeanInstanceCreator.visitBefore(BeanInstanceCreator.java:241)
        at org.milyn.delivery.sax.SAXHandler.visitBefore(SAXHandler.java:307)
        ... 40 more
```

I read and also added a dependency in d96a for mvel2 and version 2.2.0.Final. Still the same error pops up.
Using JAVA 8 What might i be doing wrong? Thanking you in advance.

EDIT: For example on running a BANSTA file for 10-12 LINs, it works fine, But when the number of LINs increase, the error pops up

**Comment by claudemamo** [comment]
We've completely overhauled EDIFACT in Smooks 2. Migrate your app to Smooks 2.0.0-M2 and re-open the issue if it persists.
