### ISSUE TITLE
Integration test failure in Milyn :: Smooks Example :: EDI-to-DB ETL module

### ISSUE THREAD

**Issue by manish-in-java** [smooks/smooks#156]
The integration test in the Milyn :: Smooks Example :: EDI-to-DB ETL module fails. Maven build output is shown below.

    Running example.DbETLTest
    log4j:WARN No appenders could be found for logger (org.milyn.util.HsqlServer).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

    ****************************************************************************************
      HTML REPORT GENERATOR IN USE!!!
      Please disable in Production mode.  This feature is a major performance drain!!
    ****************************************************************************************

    Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.807 sec <<< FAILURE! - in example.DbETLTest
    test(example.DbETLTest)  Time elapsed: 2.803 sec  <<< FAILURE!
    org.junit.ComparisonFailure: expected:<...2, ORDDATE=2006-11-1[5]}> but was:<...2, ORDDATE=2006-11-1[6]}>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at example.DbETLTest.test(DbETLTest.java:45)

    Results :

    Failed tests:
      DbETLTest.test:45 expected:<...2, ORDDATE=2006-11-1[5]}> but was:<...2, ORDDATE=2006-11-1[6]}>

    Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by manish-in-java** [comment]
The test `DbETLTest` loads data from the file `input-message.edi`, which has the header `MLS*Wed Nov 15 13:45:28 EST 2006`. The test then checks if the date read from the file is `2006-11-15`.

Since the date contains timezone information (`EST`), when run in a timezone that is ahead of UTC/GMT, the date gets read as `2006-11-16` due to the timezone difference, hence the test failure.
