### ISSUE TITLE
Java 14 ASM compatibility

### ISSUE THREAD

**Issue by ben-manes** [smooks/smooks#290]
I have trouble reproducing this and determining how it happens, but after upgrading to JDK 14 (from 11) the edi parsing sometimes fails.

On an environment I first got a class not found error,
<details>
java.lang.NoClassDefFoundError: Could not initialize class org.mvel2.compiler.ExpressionCompiler
        at org.mvel2.MVEL.compileExpression(MVEL.java:810)
        at org.mvel2.MVEL.compileExpression(MVEL.java:820)
        at org.mvel2.MVEL.compileExpression(MVEL.java:723)
        at org.milyn.expression.MVELExpressionEvaluator.setExpression(MVELExpressionEvaluator.java:55)
        at org.milyn.javabean.BeanInstanceCreator.initialize(BeanInstanceCreator.java:208)
        at jdk.internal.reflect.GeneratedMethodAccessor370.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.milyn.cdr.annotation.Configurator.invoke(Configurator.java:453)
        ... 95 common frames omitted
Wrapped by: org.milyn.cdr.SmooksConfigurationException: Error invoking @Initialize method 'initialize' on class 'org.milyn.javabean.BeanInstanceCreator'.
        at org.milyn.cdr.annotation.Configurator.invoke(Configurator.java:457)
        at org.milyn.cdr.annotation.Configurator.initialise(Configurator.java:439)
        at org.milyn.cdr.annotation.Configurator.configure(Configurator.java:91)
        at org.milyn.cdr.annotation.Configurator.configure(Configurator.java:66)
        at org.milyn.delivery.JavaContentHandlerFactory.create(JavaContentHandlerFactory.java:68)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.addCDU(ContentDeliveryConfigBuilder.java:630)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyCDUStrategy(ContentDeliveryConfigBuilder.java:562)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyStrategy(ContentDeliveryConfigBuilder.java:550)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.iterate(ContentDeliveryConfigBuilder.java:716)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.access$300(ContentDeliveryConfigBuilder.java:695)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.extractContentHandlers(ContentDeliveryConfigBuilder.java:488)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.load(ContentDeliveryConfigBuilder.java:348)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.getConfig(ContentDeliveryConfigBuilder.java:134)
        at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:91)
        at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:65)
        at org.milyn.Smooks.createExecutionContext(Smooks.java:418)
        at org.milyn.Smooks.createExecutionContext(Smooks.java:376)
        at org.milyn.Smooks.filterSource(Smooks.java:456)
        ...
Wrapped by: org.milyn.cdr.SmooksConfigurationException: Error invoking @Initialize method 'initialize' on class 'org.milyn.javabean.BeanInstanceCreator'.
        at org.milyn.cdr.annotation.Configurator.invoke(Configurator.java:457)
        at org.milyn.cdr.annotation.Configurator.initialise(Configurator.java:439)
        at org.milyn.cdr.annotation.Configurator.configure(Configurator.java:91)
        at org.milyn.cdr.annotation.Configurator.configure(Configurator.java:66)
        at org.milyn.delivery.JavaContentHandlerFactory.create(JavaContentHandlerFactory.java:68)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.addCDU(ContentDeliveryConfigBuilder.java:630)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyCDUStrategy(ContentDeliveryConfigBuilder.java:562)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$ContentHandlerExtractionStrategy.applyStrategy(ContentDeliveryConfigBuilder.java:550)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.iterate(ContentDeliveryConfigBuilder.java:716)
        at org.milyn.delivery.ContentDeliveryConfigBuilder$SmooksResourceConfigurationTableIterator.access$300(ContentDeliveryConfigBuilder.java:695)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.extractContentHandlers(ContentDeliveryConfigBuilder.java:488)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.load(ContentDeliveryConfigBuilder.java:348)
        at org.milyn.delivery.ContentDeliveryConfigBuilder.getConfig(ContentDeliveryConfigBuilder.java:134)
        at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:91)
        at org.milyn.container.standalone.StandaloneExecutionContext.<init>(StandaloneExecutionContext.java:65)
        at org.milyn.Smooks.createExecutionContext(Smooks.java:418)
        at org.milyn.Smooks.createExecutionContext(Smooks.java:376)
        at org.milyn.Smooks.filterSource(Smooks.java:456)
        ...
</details>

When trying to reproduce it locally, I got an error from `ASMAccessorOptimizer`.
<details>
INFO  [2020-04-24 19:21:14,256] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,258] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,280] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,282] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.numberOfIncludedFunctionalGroups
INFO  [2020-04-24 19:21:14,285] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,286] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.interchangeDate
INFO  [2020-04-24 19:21:14,289] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,291] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.acknowledgmentRequestedCode
INFO  [2020-04-24 19:21:14,292] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] **** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
INFO  [2020-04-24 19:21:14,293] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.repetitionSeparator
INFO  [2020-04-24 19:21:14,295] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.securityInformationQualifier
INFO  [2020-04-24 19:21:14,297] [org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer] Expression: this.securityInformationQualifier
ERROR [2020-04-24 19:21:14,312] [co.loaddocs.service.entity.environment.request.RequestSink] null
java.lang.VerifyError: (class: ASMAccessorImpl_16018523451587756074140, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getConstructor0(Class.java:3420)
	at java.base/java.lang.Class.newInstance(Class.java:585)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:746)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeSetAccessor(ASMAccessorOptimizer.java:652)
	at org.mvel2.optimizers.dynamic.DynamicSetAccessor.optimize(DynamicSetAccessor.java:83)
	at org.mvel2.optimizers.dynamic.DynamicSetAccessor.setValue(DynamicSetAccessor.java:60)
	at org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:59)
	at org.mvel2.ast.DeepAssignmentNode.getReducedValueAccelerated(DeepAssignmentNode.java:90)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.MVEL.executeExpression(MVEL.java:930)
	at org.milyn.expression.MVELExpressionEvaluator.exec(MVELExpressionEvaluator.java:99)
	at org.milyn.expression.MVELExpressionEvaluator.exec(MVELExpressionEvaluator.java:115)
	at org.milyn.javabean.BeanInstanceCreator.createAndSetBean(BeanInstanceCreator.java:295)
	at org.milyn.javabean.BeanInstanceCreator.visitBefore(BeanInstanceCreator.java:240)
	at org.milyn.delivery.sax.SAXHandler.visitBefore(SAXHandler.java:307)
	... 96 common frames omitted
Wrapped by: org.milyn.SmooksException: Error in 'org.milyn.javabean.BeanInstanceCreator' while processing the visitBefore event.
	at org.milyn.delivery.sax.SAXHandler.processVisitorException(SAXHandler.java:590)
	at org.milyn.delivery.sax.SAXHandler.processVisitorException(SAXHandler.java:576)
	at org.milyn.delivery.sax.SAXHandler.visitBefore(SAXHandler.java:319)
	at org.milyn.delivery.sax.SAXHandler.startElement(SAXHandler.java:177)
	at org.milyn.delivery.SmooksContentHandler.startElement(SmooksContentHandler.java:80)
	at org.milyn.edisax.EDIParser.startElement(EDIParser.java:875)
	at org.milyn.edisax.EDIParser.startElement(EDIParser.java:862)
	at org.milyn.edisax.EDIParser.startElement(EDIParser.java:857)
	at org.milyn.edisax.EDIParser.mapSegment(EDIParser.java:562)
	at org.milyn.edisax.EDIParser.mapSegments(EDIParser.java:535)
	at org.milyn.edisax.EDIParser.mapSegments(EDIParser.java:453)
	at org.milyn.edisax.EDIParser.parse(EDIParser.java:428)
	at org.milyn.edisax.EDIParser.parse(EDIParser.java:386)
	at org.milyn.smooks.edi.EDIReader.parse(EDIReader.java:111)
	at org.milyn.delivery.sax.SAXParser.parse(SAXParser.java:76)
	at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:86)
	... 83 common frames omitted
Wrapped by: org.milyn.SmooksException: Failed to filter source.
	at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:97)
	at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:64)
	at org.milyn.Smooks._filter(Smooks.java:526)
	at org.milyn.Smooks.filterSource(Smooks.java:482)
	at org.milyn.Smooks.filterSource(Smooks.java:456)
</details>

However sometimes it also works throughout the full run.

**Comment by claudemamo** [comment]
Which version of Smooks are you running?

**Comment by ben-manes** [comment]
1.7.1

**Comment by claudemamo** [comment]
It appears to be an issue in the MVEL dependency. Might be easier upgrading to Smooks 2 rather than troubleshooting the problem. We're close towards releasing it but a snapshot is available. The EDI/EDIFACT cartridges were rewritten to leverage DFDL and you can use the [examples](https://github.com/smooks/smooks-examples/tree/master/edifact-to-xml) for reference until the Smooks 2 docs are published.

**Comment by ben-manes** [comment]
Thank you. In the EDI usage we built out, the partner was in the midst of switching to our APIs anyway for simpler integrations. Luckily this just prompted that change without any pushback, but I imagine we'll have future EDI needs so I'm glad you've picked up maintaining this project.
