### ISSUE TITLE
Failed to start camel-csv-to-xml using Karaf

### ISSUE THREAD

**Issue by alartin** [smooks/smooks#49]
Hi all,
I tried to start Smooks 1.5.1's camel-csv-to-xml using Karaf 2.2.5 but failed. I strictly follow the readme file and make sure that I've install smooks in Karaf. The error is:

karaf@root> Exception in thread "SpringOsgiExtenderThread-22" org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route route17 at: >>> To[smooks://smooks-config.xml] <<< in route: Route[[From[xxxxx... because of Failed to resolve endpoint: smooks://smooks-config.xml due to: No component found with scheme: smooks
        at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1196)
        at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:122)
        at org.apache.camel.spring.CamelContextFactoryBean.onApplicationEvent(CamelContextFactoryBean.java:240)

You can see I've setup smooks osgi:

[  89] [Installed  ] [            ] [       ] [   60] Smooks OSGi (1.5.1)

and features list shows:

[installed  ] [1.5.1          ] smooks                                milyn-1.5.1

Why Karaf complains that it cannot find smooks component?
BTW, I've tried mvn exec:java and it worked well but only failed in Karaf

**Comment by jcordes73** [comment]
@alartin Can you do a retest with Smook 1.6, please?

**Comment by SoucianceEqdamRashti** [comment]
I get the same problem with Karaf.4.0.2 and smooks 1.7.0. Bundle is installed state and when you try to start it it says missing component smooks. I should say the same dependency works when running it from Intellij.
