### ISSUE TITLE
cannot be cast to org.smooks.engine.delivery.sax.ng.org.apache.xerces.util.SecurityManager

### ISSUE THREAD

**Issue by AbelCha0** [smooks/smooks#636]
When I use smooks with camel, the error occurs. 

XmlConverter                   WARN  DocumentBuilderFactory doesn't support the attribute http://apache.org/xml/properties/security-manager, due to class org.apache.xerces.util.SecurityManager cannot be cast to class org.smooks.engine.delivery.sax.ng.org.apache.xerces.util.SecurityManager (org.apache.xerces.util.SecurityManager and org.smooks.engine.delivery.sax.ng.org.apache.xerces.util.SecurityManager are in unnamed module of loader 'app').
java.lang.IllegalArgumentException: class org.apache.xerces.util.SecurityManager cannot be cast to class org.smooks.engine.delivery.sax.ng.org.apache.xerces.util.SecurityManager (org.apache.xerces.util.SecurityManager and org.smooks.engine.delivery.sax.ng.org.apache.xerces.util.SecurityManager are in unnamed module of loader 'app')
	at org.smooks.engine.delivery.sax.ng.org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:145) ~[smooks-core-2.0.0-RC1.jar:?]
	at org.apache.camel.converter.jaxp.XmlConverter.createDocumentBuilderFactory(XmlConverter.java:1000) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.converter.jaxp.XmlConverter.getDocumentBuilderFactory(XmlConverter.java:895) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.converter.jaxp.XmlConverter.getDocumentBuilderFactory(XmlConverter.java:956) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toDOMDocument(XmlConverter.java:722) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toDOMDocument(XmlConverter.java:709) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toDOMDocument(XmlConverter.java:736) ~[camel-xml-jaxp-3.21.0.jar:3.21.0]
	at org.apache.camel.xml.jaxb.JaxbModelToXMLDumper.dumpModelAsXml(JaxbModelToXMLDumper.java:123) ~[camel-xml-jaxb-3.21.0.jar:3.21.0]
	at org.apache.camel.xml.jaxb.JaxbModelToXMLDumper.dumpModelAsXml(JaxbModelToXMLDumper.java:157) ~[camel-xml-jaxb-3.21.0.jar:3.21.0]
	at org.apache.camel.management.mbean.ManagedCamelContext.dumpRoutesAsXml(ManagedCamelContext.java:495) ~[camel-management-3.21.0.jar:3.21.0]
	at org.apache.camel.management.mbean.ManagedCamelContext.dumpRoutesAsXml(ManagedCamelContext.java:480) ~[camel-management-3.21.0.jar:3.21.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262) ~[?:?]
	at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1178) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1172) ~[?:?]
	at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1016) ~[?:?]
	at org.apache.camel.support.management.MixinRequiredModelMBean.invoke(MixinRequiredModelMBean.java:72) ~[camel-support-3.21.0.jar:3.21.0]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:814) ~[?:?]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:802) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1472) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) [?:?]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by AbelCha0** [comment]
Add Version Info
    <dependency>
      <groupId>org.smooks.cartridges.edi</groupId>
      <artifactId>smooks-edi-cartridge</artifactId>
      <version>2.0.0-RC2</version>
    </dependency>
